#!/bin/bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
. "$SCRIPT_DIR/lib/common.sh"

RUNTIME_ROOT="$HOME/Library/Application Support/GalileoGoldenDemo"
STACK_ENV="$RUNTIME_ROOT/stack.env"
SKIP_INDEXES_ARG=""

case "${1:-}" in
  "") ;;
  --skip-indexes) SKIP_INDEXES_ARG="--skip-indexes" ;;
  -h|--help)
    printf 'Usage: %s [--skip-indexes]\n' "$0"
    exit 0
    ;;
  *) die "Unknown option: $1" ;;
esac
[ "$#" -le 1 ] || die "Usage: $0 [--skip-indexes]"

[ -f "$STACK_ENV" ] || die "Stack configuration is missing. Run install.sh --op-item first."
# Generated by install.sh with shell-escaped values and mode 0600.
# shellcheck disable=SC1090
. "$STACK_ENV"
[ -n "${OP_ITEM:-}" ] || die "This installation is not linked to a canonical 1Password item."

ARGS=(
  --op-item "$OP_ITEM"
  --refresh-config
  --model "$MLX_MODEL"
  --mlx-port "$MLX_PORT"
  --postgres-port "$POSTGRES_PORT"
  --open-webui-port "$OPEN_WEBUI_PORT"
  --app-port "$APP_PORT"
)
[ -z "${OP_VAULT:-}" ] || ARGS+=(--op-vault "$OP_VAULT")
[ -z "${OP_ACCOUNT:-}" ] || ARGS+=(--op-account "$OP_ACCOUNT")
[ "${OPENAI_ONLY:-0}" != "1" ] || ARGS+=(--openai-only)
[ "${LOCAL_ONLY:-0}" != "1" ] || ARGS+=(--local-only)
[ "${SKIP_OPEN_WEBUI:-0}" != "1" ] || ARGS+=(--skip-open-webui)
[ -z "$SKIP_INDEXES_ARG" ] || ARGS+=("$SKIP_INDEXES_ARG")

log "Refreshing deployment configuration from the canonical 1Password item"
exec "$SCRIPT_DIR/install.sh" "${ARGS[@]}"
