#!/bin/bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
. "$SCRIPT_DIR/lib/common.sh"

RUNTIME_ROOT="$HOME/Library/Application Support/GalileoGoldenDemo"
STACK_ENV="$RUNTIME_ROOT/stack.env"
OPEN_BROWSER=0

usage() {
  printf 'Usage: %s [--open]\n' "$0"
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --open) OPEN_BROWSER=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown option: $1" ;;
  esac
done

[ -f "$STACK_ENV" ] || die "Stack configuration is missing. Run scripts/macos/install.sh first."
# This file is generated by install.sh from validated numeric/path values and is
# private to the current user.
# shellcheck disable=SC1090
. "$STACK_ENV"

brew_shellenv
command_exists docker || die "Docker CLI is missing. Rerun the installer."
configure_docker_host

if ! docker info >/dev/null 2>&1; then
  command_exists colima || die "No Docker runtime is available. Rerun the installer."
  log "Starting Colima"
  colima start
  export DOCKER_HOST="unix://$HOME/.colima/default/docker.sock"
  wait_for_command 30 docker info || die "Docker did not become ready."
fi

docker_container_exists golden-demo-postgres || die "golden-demo-postgres is missing. Rerun the installer."
docker_container_running golden-demo-postgres || docker start golden-demo-postgres >/dev/null

if [ "$SKIP_OPEN_WEBUI" != "1" ]; then
  docker_container_exists galileo-open-webui || die "Open WebUI is missing. Rerun the installer."
  docker_container_running galileo-open-webui || docker start galileo-open-webui >/dev/null
fi

DOMAIN="$(launchctl_domain)"
LAUNCH_AGENTS="$HOME/Library/LaunchAgents"
if [ "$OPENAI_ONLY" != "1" ]; then
  MLX_PLIST="$LAUNCH_AGENTS/$MLX_LABEL.plist"
  [ -f "$MLX_PLIST" ] || die "MLX launch agent is missing. Rerun the installer."
  if ! launchctl print "$DOMAIN/$MLX_LABEL" >/dev/null 2>&1; then
    launchctl bootstrap "$DOMAIN" "$MLX_PLIST"
  fi
  launchctl kickstart -k "$DOMAIN/$MLX_LABEL"
fi

APP_PLIST="$LAUNCH_AGENTS/$STREAMLIT_LABEL.plist"
[ -f "$APP_PLIST" ] || die "Streamlit launch agent is missing. Rerun the installer."
if ! launchctl print "$DOMAIN/$STREAMLIT_LABEL" >/dev/null 2>&1; then
  launchctl bootstrap "$DOMAIN" "$APP_PLIST"
fi
launchctl kickstart -k "$DOMAIN/$STREAMLIT_LABEL"

log "Waiting for services"
wait_for_http "http://127.0.0.1:$APP_PORT/_stcore/health" 90 2 || die "The Galileo app did not become healthy."
if [ "$SKIP_OPEN_WEBUI" != "1" ]; then
  wait_for_http "http://127.0.0.1:$OPEN_WEBUI_PORT/health" 90 2 || die "Open WebUI did not become healthy."
fi
if [ "$OPENAI_ONLY" != "1" ]; then
  wait_for_http "http://127.0.0.1:$MLX_PORT/v1/models" 90 2 || die "MLX-LM did not become healthy."
fi

"$SCRIPT_DIR/doctor.sh" --no-fix
success "The Galileo stack is running"
printf 'Galileo app: http://127.0.0.1:%s\n' "$APP_PORT"
[ "$SKIP_OPEN_WEBUI" = "1" ] || printf 'Open WebUI:  http://127.0.0.1:%s\n' "$OPEN_WEBUI_PORT"

if [ "$OPEN_BROWSER" = "1" ]; then
  open "http://127.0.0.1:$APP_PORT"
  [ "$SKIP_OPEN_WEBUI" = "1" ] || open "http://127.0.0.1:$OPEN_WEBUI_PORT"
fi
